---
exclude: '^(?!lib/)'
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.2.3
  hooks:
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-yaml
    - id: check-xml
    - id: end-of-file-fixer
# - repo: https://github.com/pocc/pre-commit-hooks.git
#   rev: v0.2.0
#   hooks:
#     - id: clang-format
#       args: [-i]
#     - id: clang-tidy
#       args: [-checks=*, -warnings-as-errors=*]
